services:
  mysql-master:
    environment:
      SKIP_DATA_IMPORT: "true"

  backend1:
    environment:
      ENVIRONMENT: testing
      DB_SLAVE_URL: ""

  frontend:
    ports:
      - "3000:80"

volumes:
  mysql_master_test_data:
