services:
  mysql-master:
    environment:
      SKIP_DATA_IMPORT: "true"

  mysql-slave:
    profiles:
      - donotstart

  backend2:
    profiles:
      - donotstart

  backend1:
    environment:
      ENVIRONMENT: testing
      DB_SLAVE_URL: ""

  nginx-proxy:
    depends_on:
      - backend1
      - frontend

  frontend:
    ports:
      - "3000:80"

volumes:
  mysql_master_test_data:
