# Project Identification
sonar.projectKey=billing-revaktor
sonar.projectName=BillingRevaktor
sonar.projectVersion=1.0

# Source & Inclusions
# Kita persempit ke folder src saja agar tidak men-scan vendor/library/assets
sonar.sources=backend/cmd,backend/internal,backend/pkg,frontend/src
sonar.sourceEncoding=UTF-8

# Exclusions
# Tambahkan pengecualian untuk file besar dan folder aset statis
sonar.exclusions=**/node_modules/**,**/dist/**,**/release/**,backend/tmp_build/**,backend/uploads/**,**/migrations/**,**/*.spec.ts,**/*.test.ts,**/*_test.go,**/*.java,frontend/android/**,frontend/assets/**,frontend/resources/**,frontend/public/**,frontend/icons/**,frontend/bundle-analysis.html,**/*.json,**/*.html

# Backend (Go) Configuration
sonar.go.coverage.reportPaths=backend/coverage.out
sonar.go.tests.reportPaths=backend/test-report.out

# Frontend (JavaScript/TypeScript) Configuration
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Scanner Environment
sonar.host.url=http://host.docker.internal:9000
# sonar.login will be passed via command line token
